default: &default
adapter: postgresql
encoding: SQL_ASCII
host: localhost
pool: 5
username: ubuntu
password: testaroo

development:
  adapter: postgresql
  encoding: SQL_ASCII
  database: sass_development
  pool: 5
  username: ubuntu
  password: testaroo
  min_messages: WARNING

test:
  adapter: postgresql
  encoding: SQL_ASCII
  database: sass_test
  pool: 5
  username: ubuntu
  password: testaro

production:
  <<: *default
  database: sass_production
